import type { PortfolioOverview } from '../types/portfolio'

export const portfolioPreview: PortfolioOverview = {
  profile: {
    id: 1,
    username: 'abhishek-jha',
    display_name: 'Abhishek Jha',
    headline: 'Backend systems engineer turning real delivery into visible hiring signal',
    summary:
      'Builds ETL, backend platform, and cloud reliability workflows. The profile is fed by shipped work, not static claims.',
    location: 'Dallas, TX',
    primary_role: 'Senior Backend Engineer',
    contact_email: 'hello@applypilot.com',
    email: 'hello@applypilot.com',
    photo_url: '',
    hiring_status: 'open',
    hero_statement: 'Live signal over static claims. Every project, proof card, and activity entry should answer what shipped and why it mattered.',
    resume_snapshot: {
      parsed_resume_id: 301,
      file_name: 'abhishek_backend_resume.pdf',
      title: 'Senior Backend Engineer',
      updated_at: '2026-04-05T09:12:00',
    },
    metadata: {
      resume_version_count: 6,
      bootstrap_source: 'preview',
    },
    created_at: '2026-04-01T08:00:00',
    updated_at: '2026-04-05T09:12:00',
  },
  metrics: {
    impact_score: 82,
    project_count: 3,
    activity_count: 5,
    proof_count: 4,
    recent_activity_count: 3,
    tech_diversity: 8,
    resume_versions: 6,
  },
  projects: [
    {
      id: 11,
      slug: 'braintree-health-backend-engineer',
      title: 'Backend Engineer · Braintree Health',
      summary: 'Led ETL and orchestration improvements for data-heavy healthcare workflows.',
      impact_statement: 'Optimized AWS Glue pipeline and reduced runtime from 6 hours to 1.5 hours.',
      source: 'resume_experience',
      tech_stack: ['Python', 'AWS', 'Glue', 'Lambda', 'SQL'],
      bullets: [
        'Optimized AWS Glue pipeline and reduced runtime from 6 hours to 1.5 hours.',
        'Built Lambda orchestration for ETL retries and cleaner failure isolation.',
        'Clarified observability and ownership for noisy production workflows.',
      ],
      proof_points: [
        'Optimized AWS Glue pipeline and reduced runtime from 6 hours to 1.5 hours.',
        'Built Lambda orchestration for ETL retries and cleaner failure isolation.',
      ],
      links: [],
      featured: true,
      sort_order: 0,
    },
    {
      id: 12,
      slug: 'applypilot-live-identity-engine',
      title: 'ApplyPilot Live Identity Engine',
      summary: 'Turned structured resume and optimization history into a living public profile.',
      impact_statement: 'Merged resume data, proof cards, and activity logging into a single shareable profile flow.',
      source: 'resume_project',
      tech_stack: ['Vue 3', 'FastAPI', 'Postgres', 'TypeScript'],
      bullets: [
        'Built dashboard and public profile surfaces for dynamic portfolio generation.',
        'Connected proof cards to actual optimization history instead of free-form brag copy.',
      ],
      proof_points: [
        'Merged resume data, proof cards, and activity logging into a single shareable profile flow.',
      ],
      links: [],
      featured: true,
      sort_order: 1,
    },
    {
      id: 13,
      slug: 'etl-reliability-workbench',
      title: 'ETL Reliability Workbench',
      summary: 'Created a repeatable operating surface for failure handling and delivery visibility.',
      impact_statement: 'Reduced noisy retry failures by 42% with better batching and orchestration controls.',
      source: 'manual_log',
      tech_stack: ['AWS', 'Lambda', 'Step Functions', 'Python'],
      bullets: [
        'Reduced noisy retry failures by 42% with better batching and orchestration controls.',
        'Added delivery metrics and clearer incident ownership for operators.',
      ],
      proof_points: [
        'Reduced noisy retry failures by 42% with better batching and orchestration controls.',
      ],
      links: [],
      featured: false,
      sort_order: 2,
    },
  ],
  activity: [
    {
      id: 101,
      project_id: 13,
      event_type: 'manual_log',
      title: 'Shipped orchestration retry fix',
      detail: 'Handled noisy ETL retries with better fan-out control and simpler failure recovery.',
      impact: 'Reduced failure volume by 42% over the last release cycle.',
      source: 'manual_log',
      happened_on: '2026-04-05',
      tags: ['aws', 'etl', 'reliability'],
      links: [],
      visibility: 'public',
      proof: {
        claim: 'Reduced noisy retry failures by 42%.',
        evidence: 'Introduced batched retries and tuned Lambda orchestration paths.',
        metric_label: 'Failure rate',
        metric_before: '19%',
        metric_after: '11%',
      },
      created_at: '2026-04-05T16:40:00',
    },
    {
      id: 102,
      project_id: 11,
      event_type: 'manual_edit',
      title: 'Bullet edit update',
      detail: 'Strengthened the AWS pipeline bullet with clearer metric language.',
      impact: 'Improved recruiter readability and evidence density.',
      source: 'resume_version',
      happened_on: '2026-04-04',
      tags: ['resume', 'proof', 'aws'],
      links: [],
      visibility: 'public',
      proof: {
        claim: 'Clarified AWS platform ownership.',
        evidence: 'Strengthened pipeline optimization bullet.',
        metric_label: 'Score delta',
        metric_after: '+6',
      },
      created_at: '2026-04-04T11:20:00',
    },
    {
      id: 103,
      project_id: 12,
      event_type: 'bootstrap',
      title: 'Built live profile from latest resume',
      detail: 'Seeded a public profile, activity feed, and proof cards from ApplyPilot history.',
      impact: 'Created one shareable surface for current work, evidence, and resume signal.',
      source: 'resume_bootstrap',
      happened_on: '2026-04-03',
      tags: ['applypilot', 'portfolio'],
      links: [],
      visibility: 'public',
      proof: {},
      created_at: '2026-04-03T09:20:00',
    },
    {
      id: 104,
      project_id: 11,
      event_type: 'manual_log',
      title: 'Refined Glue runtime instrumentation',
      detail: 'Added tighter runtime telemetry to isolate slow segments inside the ETL graph.',
      impact: 'Made future optimization work easier to prioritize.',
      source: 'manual_log',
      happened_on: '2026-04-02',
      tags: ['glue', 'metrics'],
      links: [],
      visibility: 'public',
      proof: {},
      created_at: '2026-04-02T15:10:00',
    },
    {
      id: 105,
      project_id: 12,
      event_type: 'manual_log',
      title: 'Designed proof card model',
      detail: 'Separated claims, evidence, and metrics so the portfolio can scale beyond one-off project blurbs.',
      impact: 'Turned static portfolio content into structured proof objects.',
      source: 'manual_log',
      happened_on: '2026-04-01',
      tags: ['product', 'schema'],
      links: [],
      visibility: 'public',
      proof: {},
      created_at: '2026-04-01T13:15:00',
    },
  ],
  proof_cards: [
    {
      id: 201,
      project_id: 11,
      project_title: 'Backend Engineer · Braintree Health',
      title: 'Backend Engineer · Braintree Health',
      claim: 'Optimized AWS Glue pipeline and reduced runtime from 6 hours to 1.5 hours.',
      evidence: 'Built Lambda orchestration for ETL retries and cleaner failure isolation.',
      metric_label: 'Runtime',
      metric_before: '6h',
      metric_after: '1.5h',
      source: 'resume_experience',
      links: [],
      metadata: {
        seeded: true,
      },
      created_at: '2026-04-05T09:12:00',
    },
    {
      id: 202,
      project_id: 13,
      project_title: 'ETL Reliability Workbench',
      title: 'Shipped orchestration retry fix',
      claim: 'Reduced noisy retry failures by 42%.',
      evidence: 'Introduced batched retries and tuned Lambda orchestration paths.',
      metric_label: 'Failure rate',
      metric_before: '19%',
      metric_after: '11%',
      source: 'manual_log',
      links: [],
      metadata: {
        manual: true,
      },
      created_at: '2026-04-05T16:40:00',
    },
    {
      id: 203,
      project_id: 12,
      project_title: 'ApplyPilot Live Identity Engine',
      title: 'ApplyPilot Live Identity Engine',
      claim: 'Merged resume data, proof cards, and activity logging into a single shareable profile flow.',
      evidence: 'Connected proof cards to actual optimization history instead of free-form brag copy.',
      metric_label: '',
      metric_before: '',
      metric_after: '',
      source: 'resume_project',
      links: [],
      metadata: {
        seeded: true,
      },
      created_at: '2026-04-04T12:30:00',
    },
    {
      id: 204,
      project_id: null,
      project_title: null,
      title: 'Bullet edit update',
      claim: 'Clarified AWS platform ownership.',
      evidence: 'Strengthened pipeline optimization bullet.',
      metric_label: 'Score delta',
      metric_before: '',
      metric_after: '+6',
      source: 'resume_version',
      links: [],
      metadata: {
        version_number: 2,
      },
      created_at: '2026-04-04T11:20:00',
    },
  ],
}
