import type { PortfolioOverview } from '../types/portfolio'

export const portfolioPreview: PortfolioOverview = {
  profile: {
    id: 1,
    username: 'abhishek-jha',
    display_name: 'Abhishek Jha',
    headline: 'Distributed Systems | AI Infrastructure',
    summary: 'I build scalable backend systems and real-time pipelines.',
    location: 'Dallas, TX',
    primary_role: 'Senior Backend Engineer',
    contact_email: 'hello@applypilot.com',
    email: 'hello@applypilot.com',
    photo_url: '',
    hiring_status: 'open',
    hero_statement:
      'Focused on throughput, fault isolation, and observability across ETL, APIs, and AI-adjacent infrastructure.',
    resume_snapshot: {
      parsed_resume_id: 301,
      file_name: 'abhishek_backend_resume.pdf',
      title: 'Senior Backend Engineer',
      updated_at: '2026-04-05T09:12:00',
    },
    metadata: {
      resume_version_count: 6,
      bootstrap_source: 'preview',
    },
    created_at: '2026-04-01T08:00:00',
    updated_at: '2026-04-05T09:12:00',
  },
  metrics: {
    impact_score: 86,
    project_count: 3,
    activity_count: 5,
    proof_count: 4,
    recent_activity_count: 5,
    tech_diversity: 8,
    resume_versions: 6,
  },
  projects: [
    {
      id: 11,
      slug: 'braintree-health-backend-engineer',
      title: 'AWS ETL Reliability Program',
      summary: 'Nightly healthcare ETL jobs were missing their windows and creating noisy retry storms.',
      impact_statement: 'Reduced runtime from 6 hours to 1.5 hours by redesigning the AWS Glue and Lambda path.',
      source: 'resume_experience',
      tech_stack: ['Python', 'AWS', 'Glue', 'Lambda', 'SQL'],
      bullets: [
        'Restructured Glue stages and parallelized expensive transforms to shrink end-to-end runtime.',
        'Built Lambda retry orchestration with batch isolation so bad payloads stopped poisoning whole runs.',
        'Added clearer runtime telemetry and ownership paths for operators.',
      ],
      proof_points: [
        'Designed Lambda orchestration with batched retries and failure isolation.',
        'Instrumented slow stages so follow-up optimizations were measurable.',
      ],
      links: [],
      featured: true,
      sort_order: 0,
    },
    {
      id: 12,
      slug: 'applypilot-public-signal-engine',
      title: 'ApplyPilot Public Signal Engine',
      summary: 'Resume edits, proof objects, and activity data lived in separate surfaces with no recruiter-facing narrative.',
      impact_statement: 'Unified resume data, proof cards, and live activity into one shareable profile flow.',
      source: 'resume_project',
      tech_stack: ['Vue 3', 'FastAPI', 'Postgres', 'TypeScript'],
      bullets: [
        'Built the public profile surface and dashboard tooling on a shared portfolio schema.',
        'Mapped proof cards to actual optimization history instead of static portfolio copy.',
      ],
      proof_points: [
        'Connected resume versions, activity logs, and proof cards into a single public identity layer.',
      ],
      links: [],
      featured: true,
      sort_order: 1,
    },
    {
      id: 13,
      slug: 'etl-reliability-workbench',
      title: 'ETL Reliability Workbench',
      summary: 'Operators needed a repeatable way to control retries, isolate bad batches, and see delivery health.',
      impact_statement:
        'Reduced noisy retry failures by 42% with batching, orchestration controls, and clearer recovery paths.',
      source: 'manual_log',
      tech_stack: ['AWS', 'Lambda', 'Step Functions', 'Python'],
      bullets: [
        'Introduced safer retry batching so failure-heavy jobs stopped cascading across the workflow.',
        'Added delivery metrics and clearer incident ownership for operators.',
      ],
      proof_points: [
        'Introduced batched retries and safer orchestration boundaries for retry-heavy jobs.',
        'Added delivery metrics that made incident triage faster.',
      ],
      links: [],
      featured: true,
      sort_order: 2,
    },
  ],
  activity: [
    {
      id: 101,
      project_id: 13,
      event_type: 'manual_log',
      title: 'Shipped orchestration retry fix',
      detail: 'Reworked fan-out control and recovery boundaries for noisy ETL retries.',
      impact: 'Reduced retry-related failures by 42% over the last release cycle.',
      source: 'manual_log',
      happened_on: '2026-04-05',
      tags: ['aws', 'etl', 'reliability'],
      links: [],
      visibility: 'public',
      proof: {
        claim: 'Reduced noisy retry failures by 42%.',
        evidence: 'Introduced batched retries and tuned Lambda orchestration paths.',
        metric_label: 'Failure rate',
        metric_before: '19%',
        metric_after: '11%',
      },
      created_at: '2026-04-05T16:40:00',
    },
    {
      id: 102,
      project_id: 11,
      event_type: 'manual_log',
      title: 'Expanded Glue runtime telemetry',
      detail: 'Instrumented stage-level runtime and retry checkpoints across the ETL graph.',
      impact: 'Made slow-path regressions obvious before the next optimization pass.',
      source: 'manual_log',
      happened_on: '2026-04-04',
      tags: ['observability', 'glue', 'metrics'],
      links: [],
      visibility: 'public',
      proof: {
        claim: 'Surfaced stage-level runtime across the ETL graph.',
        evidence: 'Added telemetry around retry boundaries and slow transforms.',
        metric_label: 'Coverage',
        metric_after: 'End-to-end',
      },
      created_at: '2026-04-04T11:20:00',
    },
    {
      id: 103,
      project_id: 12,
      event_type: 'bootstrap',
      title: 'Launched public signal pipeline',
      detail: 'Connected resume history, proof cards, and live activity into one recruiter-facing profile.',
      impact: 'Created a single shareable artifact for shipped work and current momentum.',
      source: 'resume_bootstrap',
      happened_on: '2026-04-03',
      tags: ['fastapi', 'postgres', 'portfolio'],
      links: [],
      visibility: 'public',
      proof: {},
      created_at: '2026-04-03T09:20:00',
    },
    {
      id: 104,
      project_id: 13,
      event_type: 'manual_log',
      title: 'Hardened ETL batching strategy',
      detail: 'Introduced tighter batch sizing to prevent retry storms during peak windows.',
      impact: 'Improved failure isolation and reduced operator noise.',
      source: 'manual_log',
      happened_on: '2026-04-02',
      tags: ['lambda', 'step-functions', 'batching'],
      links: [],
      visibility: 'public',
      proof: {},
      created_at: '2026-04-02T15:10:00',
    },
    {
      id: 105,
      project_id: 12,
      event_type: 'manual_log',
      title: 'Modeled proof-backed portfolio objects',
      detail: 'Separated claims, evidence, metrics, and activity history into reusable portfolio entities.',
      impact: 'Turned static portfolio content into a scalable system of proof.',
      source: 'manual_log',
      happened_on: '2026-04-01',
      tags: ['schema', 'api', 'signal'],
      links: [],
      visibility: 'public',
      proof: {},
      created_at: '2026-04-01T13:15:00',
    },
  ],
  proof_cards: [
    {
      id: 201,
      project_id: 11,
      project_title: 'AWS ETL Reliability Program',
      title: 'AWS ETL Reliability Program',
      claim: 'Reduced AWS ETL runtime from 6 hours to 1.5 hours.',
      evidence: 'Redesigned Glue stages and added Lambda orchestration with failure isolation.',
      metric_label: 'Runtime',
      metric_before: '6h',
      metric_after: '1.5h',
      source: 'resume_experience',
      links: [],
      metadata: {
        seeded: true,
      },
      created_at: '2026-04-05T09:12:00',
    },
    {
      id: 202,
      project_id: 13,
      project_title: 'ETL Reliability Workbench',
      title: 'Shipped orchestration retry fix',
      claim: 'Reduced noisy retry failures by 42%.',
      evidence: 'Introduced batched retries and tuned Lambda orchestration paths.',
      metric_label: 'Failure rate',
      metric_before: '19%',
      metric_after: '11%',
      source: 'manual_log',
      links: [],
      metadata: {
        manual: true,
      },
      created_at: '2026-04-05T16:40:00',
    },
    {
      id: 203,
      project_id: 12,
      project_title: 'ApplyPilot Public Signal Engine',
      title: 'ApplyPilot Public Signal Engine',
      claim: 'Unified resume data, proof cards, and live activity into one recruiter-facing flow.',
      evidence: 'Shipped a shared portfolio schema across dashboard and public profile surfaces.',
      metric_label: 'Signals unified',
      metric_before: '',
      metric_after: '3',
      source: 'resume_project',
      links: [],
      metadata: {
        seeded: true,
      },
      created_at: '2026-04-04T12:30:00',
    },
    {
      id: 204,
      project_id: 11,
      project_title: 'AWS ETL Reliability Program',
      title: 'Expanded Glue runtime telemetry',
      claim: 'Instrumented Glue runtime to expose slow stages earlier.',
      evidence: 'Added telemetry around retry boundaries and expensive transforms.',
      metric_label: 'Coverage',
      metric_before: '',
      metric_after: 'End-to-end',
      source: 'manual_log',
      links: [],
      metadata: {
        manual: true,
      },
      created_at: '2026-04-04T11:20:00',
    },
  ],
}
